### ISSUE TITLE
Week 7 homework

### ISSUE THREAD

**Issue by Kenneffy** [angelica3010/week7train#1]
Hello Angel, it seems like values from your forms are being pushed up but results from firebase aren't rendering on the screen. Looks like that's where you stopped off in your app.js, just need to append those elements using .append(). You're also at the part where you're suppose to calculate the minutes until arrival. Here's a little hint, try using the % (modulus) to find the remainder of two values. Keep at it!

**Comment by angelica3010** [comment]
Confirming this has been updated! Thanks!
